#! /bin/sh


# turn on logging
set -xv
exec 2>>/tmp/bspwm.log



bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor DP-3 -d 6 7 8 9 0
pkill polybar
polybar &
pkill sxhkd
sxhkd &
polybar &
pkill feh
~/.fehbg &
pkill picom
picom --config ~/.config/picom/picom.conf &
libinput-gestures-setup start
pkill wireplumber

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config normal_border_color "#282828"
bspc config focused_border_color "#ea6962"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

