#! /bin/sh

pkill feh
~/.fehbg &
pkill sxhkd
sxhkd &
pkill picom
picom --config ~/.config/picom/picom.conf &
libinput-gestures-setup start &
pkill wireplumber


if xrandr | grep "eDP-1-1"; then
  bspc monitor eDP-1-1 -d 1 2 3 4 5 &
else
  if xrandr | grep "DP-3 connected"; then
    bspc monitor eDP-1 -d 6 7 8 9 0 &
    bspc monitor DP-3 -d 1 2 3 4 5 &
  else
    bspc monitor eDP-1 -d 1 2 3 4 5 &
  fi
fi
~/.config/polybar/material/launch.sh &
bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config normal_border_color "#1F1F1F"
bspc config focused_border_color "#e53935"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
kitty paru -Syu --noconfirm
