git:
  diffRenderers:
    - colorArg: always
      command: diff-so-fancy
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
