#! /bin/sh

# hotsplug monitors

if xrandr | grep "eDP-1-1"; then
  PRIMARY="eDP-1-1"
  SECONDARY="DP-0"
  xrandr --output $PRIMARY --auto --primary
  xrandr --output $SECONDARY --auto --right-of $PRIMARY
  bspc monitor eDP-1-1 -d 6 7 8 9 0
  bspc monitor DP-0 -d 1 2 3 4 5
elif xrandr | grep "DP-2 connected"; then
  PRIMARY="DP-2"
  SECONDARY="eDP-1"
  xrandr --output $PRIMARY --auto --primary
  xrandr --output $SECONDARY --auto --left-of $PRIMARY
  bspc monitor eDP-1 -d 1 2 3 4 5
  bspc monitor DP-2 -d 6 7 8 9 0
else
  echo "No external monitor detected"
fi

~/.fehbg
~/.config/polybar/material/launch.sh

