#! /bin/bash

# update all thedotfiles and then make a commit
cd $HOME/dotfiles
cp -r ~/.config/nvim/ ~/dotfiles/
cp -r ~/.config/alacritty/ ~/dotfiles/
cp -r ~/.config/polybar/ ~/dotfiles/
cp -r ~/.config/rofi/ ~/dotfiles/
cp -r ~/.config/scripts/ ~/dotfiles/
cp -r ~/.config/libinput-gestures.conf ~/dotfiles/libinput-gestures.conf
cp -r ~/.config/sxhkd/ ~/dotfiles/sxhkd/
cp ~/.p10k.zsh ~/dotfiles/zsh/.p10k.zsh
cp ~/.zshrc ~/dotfiles/zsh/.zshrc
cp ~/.zlogin ~/dotfiles/zsh/.zlogin
cp ~/.zshenv ~/dotfiles/zsh/.zshenv
git add --all
git commit -m "update $(date)"
